server:
  port: 8084 

spring:
  application:
    name: servicio-administrador

  datasource:
    url: jdbc:postgresql://ep-dark-flower-acxgvu5x-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_8DrnxkMa1gcj
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:

 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: https://eureka-server-wp64.onrender.com/eureka/
 instance:
  prefer-ip-address: false
  hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
  secure-port-enabled: true
  secure-port: 443
  non-secure-port-enabled: false
  home-page-url: https://${RENDER_EXTERNAL_HOSTNAME}/
  status-page-url: https://${RENDER_EXTERNAL_HOSTNAME}/actuator/info
  health-check-url: https://${RENDER_EXTERNAL_HOSTNAME}/actuator/health


springdoc:
 api-docs:
  enabled: true
 swagger-ui:
  enabled: true
  path: /doc/swagger-ui.html